# Generated by Django 6.0.1 on 2026-01-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('stu_class', models.IntegerField()),
                ('rollno', models.IntegerField(unique=True)),
                ('section', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
