# Generated by Django 6.0.1 on 2026-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_address_alter_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
